# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-ios-list' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'Kingfisher', '~> 4.0'
  pod 'SVProgressHUD', '~> 2.2'

  # Pods for github-ios-list

  target 'github-ios-listTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github-ios-listUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
